#!/bin/bash

echo "🛑 批量取消重复工作流指南"
echo "=========================="
echo "时间: $(date)"
echo ""

echo "❌ 问题原因:"
echo "• 工作流配置了多个触发条件"
echo "• 每次推送main分支都触发新运行"
echo "• push + tags + workflow_dispatch + pull_request"
echo "• 导致了大量重复的并行运行"
echo ""

echo "✅ 已修复配置:"
echo "1. ✅ 移除 branches: [main] 触发"
echo "2. ✅ 移除 pull_request 触发"
echo "3. ✅ 只保留 tags 和 workflow_dispatch"
echo "4. ✅ 添加手动构建类型选择"
echo "5. ✅ 禁用 test-simple.yml 自动触发"
echo ""

echo "🛑 现在需要手动取消所有运行中的工作流:"
echo ""
echo "步骤1: 访问 GitHub Actions 页面"
echo "https://github.com/miaokela/query-builder/actions"
echo ""
echo "步骤2: 取消所有状态为以下的工作流:"
echo "• 🟡 In progress (正在运行)"
echo "• 🔵 Queued (排队等待)"
echo "• 🟠 Pending (等待中)"
echo ""
echo "步骤3: 对每个运行中的工作流:"
echo "• 点击工作流条目"
echo "• 点击右上角 'Cancel workflow' 按钮"
echo "• 确认取消"
echo ""

echo "🔍 需要取消的工作流类型:"
echo "• Build and Release (主构建)"
echo "• Simple Test Build (测试构建)"
echo "• 任何重复的运行"
echo ""

echo "✅ 取消完成后验证:"
echo "• 所有工作流状态显示为 ❌ Cancelled"
echo "• 没有黄色🟡或蓝色🔵的运行状态"
echo "• Actions页面顶部显示无活动运行"
echo ""

echo "🎯 取消完成后的正确使用方式:"
echo ""
echo "方式1: 测试构建 (推荐)"
echo "• 访问: https://github.com/miaokela/query-builder/actions/workflows/build.yml"
echo "• 点击 'Run workflow'"
echo "• 选择 build_type: 'test'"
echo "• 只构建，不发布"
echo ""
echo "方式2: 完整发布"
echo "• 方式2a: 手动触发 + 选择 'release'"
echo "• 方式2b: 推送新标签 (会自动发布)"
echo ""

echo "⚠️  重要提醒:"
echo "• 新配置下，只有标签推送或手动触发会运行"
echo "• 普通代码推送不再触发构建"
echo "• 这样可以避免重复运行"
echo ""

echo "📱 下一步:"
echo "1. 立即取消所有运行中的工作流"
echo "2. 推送修复后的配置"
echo "3. 手动测试新的触发机制"